package it.polimi.ingsw.util;

import java.util.List;
import java.util.Random;

public class EasterEgg {

    private static final List<String> JOKES = List.of(
            "When {name} throws exceptions, it's across the room.",
            "All arrays {name} declares are of infinite size, because {name} knows no bounds.",
            "{name} doesn't have disk latency because the hard drive knows to hurry the hell up, or else.",
            "{name} writes code that optimises itself.",
            "{name} can't test for equality because he has no equal.",
            "{name} doesn't need garbage collection because he doesn't call .Dispose(), he calls .DropKick().",
            "{name}'s first program was kill -9.",
            "{name} burst the dot com bubble.",
            "MySpace isn't really your space, it's {name}'s (he just lets you use it).",
            "{name} can write infinitely recursive functions and have them return.",
            "{name} can solve the Towers of Hanoi in one move.",
            "The only design pattern {name} knows is the God Object Pattern.",
            "{name} finished World of Warcraft.",
            "Project managers never ask {name} for estimations.",
            "{name} doesn't use web standards as the web will conform to him.",
            "'It works on my machine' always holds true for {name}.",
            "{name} doesn't do Burn Down charts, he does Smack Down charts.",
            "{name} can delete the Recycling Bin.",
            "{name}'s beard can type 140 words per minute.",
            "{name} can unit test entire applications with a single assertion, 'it works'.",
            "{name} doesn't bug hunt as that signifies a probability of failure, he goes bug killing.",
            "{name}'s keyboard doesn't have a Ctrl key because nothing controls {name}.",
            "{name} can overflow your stack just by looking at it.",
            "To {name}, everything contains a vulnerability.",
            "{name} doesn't sudo, the shell just knows it's him and does what it's told.",
            "{name} doesn't need a debugger, he just stares at the code until it confesses.",
            "{name} can access private methods.",
            "{name} can instantiate an abstract class.",
            "{name} does not need to know about Class Factory Pattern. He can instantiate interfaces.",
            "The class object inherits from {name}.",
            "For {name}, NP-Hard = O(1).",
            "{name} knows the last digit of Pi.",
            "{name}'s Internet connection is faster upstream than downstream because even data has more incentive to run from him than to him.",
            "{name} solved the Travelling Salesman problem in O(1) time: break salesman into N pieces; kick each piece to a different city.",
            "No statement can catch the {name}Exception.",
            "{name} doesn't pair program.",
            "{name} can write multi-threaded applications with a single thread.",
            "{name} doesn't need to use AJAX because pages are too afraid to postback anyways.",
            "{name} doesn't use reflection, reflection asks politely for his help.",
            "There is no Esc key on {name}'s keyboard, because no one escapes {name}.",
            "{name} can binary search unsorted data.",
            "{name} doesn't need try-catch, exceptions are too afraid to raise.",
            "{name} went out of an infinite loop.",
            "If {name} writes code with bugs, the bugs fix themselves.",
            "{name} hosting is 101% uptime guaranteed.",
            "{name}'s keyboard has the Any key.",
            "{name} can access the database from the UI.",
            "{name}'s programs never exit, they are terminated.",
            "{name} insists on strongly-typed programming languages.",
            "The {name} protocol design method has no status, requests or responses, only commands.",
            "{name}'s programs occupy 150% of CPU, even when they are not running.",
            "{name} can spawn threads that complete before they are started.",
            "{name}'s programs do not accept input.",
            "{name} can install iTunes without installing Quicktime.",
            "{name} doesn't need an OS.",
            "{name}'s OSI network model has only one layer - Physical.",
            "{name} can compile syntax errors.",
            "Every SQL statement that {name} codes has an implicit 'COMMIT' in its end.",
            "{name} does not code in cycles, he codes in strikes.",
            "{name} compresses his files by doing a flying round house kick to the hard drive.",
            "Chuck {name} solved the halting problem.",
            "With {name} P = NP. There's no nondeterminism with {name}'s decisions.",
            "{name} can retrieve anything from /dev/null.",
            "No one has ever pair-programmed with {name} and lived to tell the tale.",
            "No one has ever spoken during review of {name}'s code and lived to tell the tale.",
            "{name} doesn't use a GUI, he prefers COMMAND line.",
            "{name} doesn't use Oracle, he is the Oracle.",
            "{name} can dereference NULL.",
            "A diff between your code and {name}'s is infinite.",
            "The {name} Eclipse plugin made alien contact.",
            "{name} is the ultimate mutex, all threads fear him.",
            "Don't worry about tests, {name}'s test cases cover your code too.",
            "Each hair in {name}'s beard contributes to make the world's largest DDOS.",
            "{name}'s log statements are always at the FATAL level.",
            "{name}'s database has only one table, 'Kick', which he drops frequently.",
            "{name} completed World of Warcraft.",
            "When {name} breaks the build, you can't fix it, because there is not a single line of code left.",
            "{name} types with one finger. He points it at the keyboard and the keyboard does the rest.",
            "{name}'s programs can pass the Turing Test by staring at the interrogator.",
            "If you try to kill -9 {name}'s programs, it backfires.",
            "{name} performs infinite loops in under 4 seconds.",
            "{name} can overwrite a locked variable.",
            "{name} knows the value of NULL, and he can sort by it too.",
            "{name} can install a 64-bit operating system on 32-bit machines.",
            "{name} can write to an output stream.",
            "{name} can read from an input stream.",
            "{name} never has to build his program to machine code. Machines have learnt to interpret {name}'s code.",
            "{name}'s unit tests don't run. They die.",
            "{name} causes the Blue Screen of Death.",
            "{name} can make a class that is both abstract and final.",
            "{name} could use anything in java.util.* to kill you, including the javadocs.",
            "Code runs faster when {name} watches it.",
            "{name} doesn't use REST, he waits.",
            "Everyone likes {name} on Facebook, whether they choose to or not.",
            "You can't follow {name} on Twitter, because he follows you.",
            "{name}'s calculator has only 3 keys: 0, 1, and NAND.",
            "{name} only uses global variables. He has nothing to hide.",
            "{name} once implemented an HTTP server in a single printf call. It is now the heart of Apache webserver.",
            "{name} writes directly in binary. He then writes the source code as documentation for other programmers.",
            "{name} once shifted a bit so hard, it ended up on a different computer.",
            "Q: What is {name}'s favorite Javascript framework? A: Knockout.js."
    );

    private static final Random RANDOM = new Random();

    public static String getRandomJoke(String name) {
        String joke = JOKES.get(RANDOM.nextInt(JOKES.size()));
        return joke.replace("{name}", name);
    }
}
